import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-input-button-unit',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './input-button-unit.component.html',
  styleUrl: './input-button-unit.component.scss'
})

export class InputButtonUnitComponent {

  title = 'Hello World';

  constructor() { 

    setTimeout(() => {
      this.title = 'This is not the title you are looking for';
    }, 3000);
    
  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }

}

function multiply (x: number, y: number): number {
  return x * y;
}

let z = multiply(4, 5);
console.log(z);
